FROM nginx:latest


RUN apt-get update && apt-get install -y passwd


COPY ./docker/build/default.conf /etc/nginx/conf.d/

RUN echo "upstream php-upstream { server demo_php:9000; }" > /etc/nginx/conf.d/upstream.conf


RUN usermod -u 1000 www-data


EXPOSE 80
