FROM php:8.2-fpm

# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    zlib1g-dev \
    libxml2-dev \
    libpng-dev \
    libzip-dev \
    vim \
    curl \
    debconf \
    subversion \
    apt-transport-https \
    apt-utils \
    build-essential \
    locales \
    acl \
    mailutils \
    wget \
    nodejs \
    zip \
    unzip \
    gnupg \
    sudo \
    ssh \
    && docker-php-ext-install \
    pdo_mysql \
    soap \
    zip \
    opcache \
    gd \
    intl \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Install Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony*/bin/symfony /usr/local/bin/symfony


# Copy PHP configuration files
COPY ./docker/build/php/opcache.ini /usr/local/etc/php/conf.d/
COPY ./docker/build/php/error_reporting.ini /usr/local/etc/php/conf.d/

# Set working directory
WORKDIR /var/www/symfony

# Copy application files
COPY . /var/www/symfony

# Set permissions for the application directory
RUN mkdir -p /var/www/symfony/var \
    && chown -R www-data:www-data /var/www/symfony \
    && chmod -R 777 /var/www/symfony/var

# Switch to the www-data user
USER www-data

# Install Symfony dependencies
RUN composer install
#--no-dev --optimize-autoloader --no-scripts

# Expose PHP-FPM port
EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm"]
