version: "3.7"
services:
  fpm:
    container_name: demo_php
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./:/var/www/demo/:cached
    environment:
      # Enhanced Xdebug configuration
      PHP_IDE_CONFIG: "serverName=symfony-docker"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION_START: 1
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        start_with_request=yes
        log_level=7
        log=/tmp/xdebug.log
    # Ensure these ports are exposed for Xdebug
    expose:
      - 9003
    networks:
      - app_network

  nginx:
    container_name: demo_nginx
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    volumes:
      - ./:/var/www/demo/:cached
    ports:
      - 8080:80
    depends_on:
      - fpm
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database_data:
