version: "3.7"

services:
  fpm:
    container_name: demo_php
    build:
      context: .
      dockerfile: Dockerfile-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/demo/:cached
    environment:
      # Enhanced Xdebug configuration (optional, only if using Xdebug)
      PHP_IDE_CONFIG: "serverName=symfony-docker"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION_START: 1
    expose:
      - 9003
    networks:
      - app_network

  nginx:
    container_name: demo_nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/demo/:cached
    ports:
      - 8080:80
    depends_on:
      - fpm
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database_data:
