FROM nginx:alpine

# Install utilities
RUN apk add --no-cache bash curl

# Copy custom NGINX configuration
COPY ./docker/build/default.conf /etc/nginx/conf.d/default.conf

# Expose NGINX port
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
