name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the PHP image
      - name: Build and Push PHP Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-php
          push: true
          tags: |
            muneer1997/demo_php:latest
            muneer1997/demo_php:${{ github.sha }}

      # Step 5: Build and push the Nginx image
      - name: Build and Push Nginx Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-nginx
          push: true
          tags: |
            muneer1997/demo_nginx:latest
            muneer1997/demo_nginx:${{ github.sha }}
